### ISSUE TITLE
大佬是否可以升级一波依赖，似乎好多包版本过旧，例如typescript版本过低，vscode会有警告提示，以及pnpm@8以上，lock文件也有较大变化

### ISSUE THREAD

**Issue by seepine** [bfehub/vlib-starter#10]
![image](https://github.com/bfehub/vlib-starter/assets/93666053/29c1ac0f-0453-4b87-ab83-b26628a5d73c)

**Comment by haiweilian** [comment]
在更了，上周刚把规范工具项目更新完，还要改文章会慢点。
