### ISSUE TITLE
是否有计划支持多语言呢，例如arco这样通过README后缀区分

### ISSUE THREAD

**Issue by seepine** [bfehub/vlib-starter#14]
https://github.com/arco-design/arco-design-vue/tree/main/packages/web-vue/components/button

![image](https://github.com/bfehub/vlib-starter/assets/93666053/85637159-ff74-43b5-a004-d2992d7ef42a)

**Comment by haiweilian** [comment]
vuepress 默认支持，现在也是有预留的搜索 `zh` 关键字相关的地方。想用高级点的功能看 https://github.com/bfehub/vmi。
